# nxlog.conf
# Forwards Windows Event Logs (Application, System, Security) to Graylog via GELF UDP
# Used on DC01 and Client-01
# Author: Ibnousoufyane Ayman

define ROOT C:\Program Files\nxlog
Moduledir %ROOT%\modules
CacheDir  %ROOT%\data
Pidfile   %ROOT%\data\nxlog.pid
SpoolDir  %ROOT%\data
LogFile   %ROOT%\data\nxlog.log

<Extension gelf>
    Module      xm_gelf
</Extension>

<Input eventlog>
    Module      im_msvistalog
    Query <QueryList>\
            <Query Id="0">\
                <Select Path="Application">*</Select>\
                <Select Path="System">*</Select>\
                <Select Path="Security">*</Select>\
            </Query>\
        </QueryList>
</Input>

<Output graylog>
    Module      om_udp
    Host        192.168.1.101
    Port        12201
    OutputType  GELF
</Output>

<Route windows_to_graylog>
    Path        eventlog => graylog
</Route>
